### ISSUE TITLE
Unable to update plugin

### ISSUE THREAD

**Issue by chappers00** [Big-Tree/HomeAssistant-OptiSpark#30]
### System Health details

N/A

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Big-Tree/HomeAssistant-OptiSpark/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:730
Integration: HACS (documentation, issues)
First occurred: 2:45:45 PM (2 occurrences)
Last logged: 2:55:25 PM

Download failed - Got status code 404 when trying to download https://github.com/Big-Tree/HomeAssistant-OptiSpark/releases/download/main/optispark.zip
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 730, in async_download_file
    raise HacsException(
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/Big-Tree/HomeAssistant-OptiSpark/releases/download/main/optispark.zip

### Reproduction steps

1. Go to the HACS console
2. Find the update option for Optispark
3. Click update - you get a spinner
...

### Debug logs

```text
See describe the issue section
```

**Comment by Big-Tree** [comment]
Thanks for reporting that!  Should now be fixed in commit 9f553b5.
hacs.json was configured incorrectly and for some reason was causing issues only now.
https://github.com/Big-Tree/HomeAssistant-OptiSpark/blob/08e596ae90075d0d4c72f8f21e20df53e6eb4ef4/hacs.json#L1-L7

**Comment by chappers00** [comment]
Thanks!
